version: '3'

services:
  memos:
    image: lclrc/memos-wechat-proxy:latest
    container_name: memos-wechat-proxy
    ports:
      - 5000:5000
    volumes:
      - ~/memos-wechat-proxy/config.ini:/app/config.ini
