version: '3'

services:
  memos:
    image: zhaoweiping/memos-proxy:latest 
    container_name: memos-proxy
    ports:
      - 5000:5000
    volumes:
      - /data/go/memos-proxy/config.ini:/app/config.ini