services:
  memos:
    image: neosmemo/memos:0.14.4
    container_name: memos
    volumes:
      - ./data:/var/opt/memos
    ports:
      - 127.0.0.1:5230:5230

  memos-wechat-proxy:
    image: shiguang2021/memos-wechat-proxy
    container_name: memos-wechat-proxy
    ports:
      - "5000:5000"
    volumes:
      - ./config:/config